// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZeaoCuxi98rFe49AJFcbB1X6YcJlBALs',
    appId: '1:71986301547:web:9f9eed9ab8e1daae057f2e',
    messagingSenderId: '71986301547',
    projectId: 'nyayamitra-app',
    authDomain: 'nyayamitra-app.firebaseapp.com',
    storageBucket: 'nyayamitra-app.firebasestorage.app',
    measurementId: 'G-WQZJN6WQS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnPeF1zmE-Wug_whfv48ZVn0hd6E5sjn0',
    appId: '1:402149525141:android:79c6526107cb4312ad7d9c',
    messagingSenderId: '402149525141',
    projectId: 'nyaya-mitra-app',
    storageBucket: 'nyaya-mitra-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9PikDHtjo7JB8peG1xXsJyEt_vy5PKbw',
    appId: '1:71986301547:ios:52c1d2fd24372ad6057f2e',
    messagingSenderId: '71986301547',
    projectId: 'nyayamitra-app',
    storageBucket: 'nyayamitra-app.firebasestorage.app',
    iosBundleId: 'com.example.legalInfoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9PikDHtjo7JB8peG1xXsJyEt_vy5PKbw',
    appId: '1:71986301547:ios:52c1d2fd24372ad6057f2e',
    messagingSenderId: '71986301547',
    projectId: 'nyayamitra-app',
    storageBucket: 'nyayamitra-app.firebasestorage.app',
    iosBundleId: 'com.example.legalInfoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZeaoCuxi98rFe49AJFcbB1X6YcJlBALs',
    appId: '1:71986301547:web:fbd776cf096db69f057f2e',
    messagingSenderId: '71986301547',
    projectId: 'nyayamitra-app',
    authDomain: 'nyayamitra-app.firebaseapp.com',
    storageBucket: 'nyayamitra-app.firebasestorage.app',
    measurementId: 'G-Q3V2BC4LKN',
  );
}